// This code is automatically generated by MAO Timeline Playable Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

public class MAOFlareAndParaBehaviour : PlayableBehaviour
{
    public float FlareInstensity;
    public int FlareInteration;
    public Color InnerColor;
    public Color OuterColor;
    public float ColorMixedMidPoint;
    public float ColorMixedSoftness;
    public float FlareRange;
    public bool RotateWithMainLight;
    public float ExtraRotation;
    public float ParaIntensity;
    public float ParaRange;
    public float ParaRotation;

}
