// This code is automatically generated by MAO Timeline Playable Wizard.
// For more information, please visit 
// https://github.com/ShiinaRinne/TimelineExtensions

using System;
using UnityEngine;
using UnityEngine.Timeline;
using UnityEngine.Playables;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

[Serializable]
public class MAOFlareAndParaClip : PlayableAsset, ITimelineClipAsset
{
    [Range(0f, 1f)] public float flareInstensity = 0f;
    [Range(0, 0)] public int flareInteration = 4;
    public Color innerColor = new Color(0.653071f, 0.8207547f, 0.5768512f, 1f);
    public Color outerColor = new Color(0.6196079f, 0.3921569f, 0.509804f, 1f);
    [Range(-2f, 2f)] public float colorMixedMidPoint = -1.09f;
    [Range(0f, 2f)] public float colorMixedSoftness = 0f;
    [Range(-5f, 5f)] public float flareRange = -0.3f;
    public bool rotateWithMainLight = false;
    [Range(0f, 360f)] public float extraRotation = 0f;
    [Range(0f, 1f)] public float paraIntensity = 0.11f;
    [Range(-5f, 5f)] public float paraRange = -1.2f;
    [Range(0f, 360f)] public float paraRotation = 0f;


    public ClipCaps clipCaps
    {
        get { return ClipCaps.Blending; }
    }

    public override Playable CreatePlayable(PlayableGraph graph, GameObject owner)
    {
        var playable = ScriptPlayable<MAOFlareAndParaBehaviour>.Create(graph);
        var behaviour = playable.GetBehaviour();

        behaviour.FlareInstensity = flareInstensity;
        behaviour.FlareInteration = flareInteration;
        behaviour.InnerColor = innerColor;
        behaviour.OuterColor = outerColor;
        behaviour.ColorMixedMidPoint = colorMixedMidPoint;
        behaviour.ColorMixedSoftness = colorMixedSoftness;
        behaviour.FlareRange = flareRange;
        behaviour.RotateWithMainLight = rotateWithMainLight;
        behaviour.ExtraRotation = extraRotation;
        behaviour.ParaIntensity = paraIntensity;
        behaviour.ParaRange = paraRange;
        behaviour.ParaRotation = paraRotation;


        return playable;
    }
}
